name: Mirror

on:
  push:
  workflow_dispatch:
  
jobs:
  Push-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Test github gpg key
        env:
            SEC_PASS: ${{ secrets.SEC_PASS }}
            SEC_KEY: ${{ secrets.SEC_KEY }}
        run: |
            echo "Jai ho"
            bash ./scripts/trigger.sh
            