name: Mirror

on:
  push:
  workflow_dispatch:
  
jobs:
  Updating_dist:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Test github gpg key
        env:
            SEC_PASS: ${{ secrets.SEC_PASS }}
            SEC_KEY: ${{ secrets.SEC_KEY }}
        run: |
            echo "Jai ho"
            bash ./scripts/trigger.sh
            