name: auto-build

on:
  push:
  workflow_dispatch:
  
jobs:
  Updating_dist:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: updating and signing releases file
        env:
            SEC_PASS: ${{ secrets.SEC_PASS }}
            SEC_KEY: ${{ secrets.SEC_KEY }}
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            echo "Jai ho"
            bash ./scripts/trigger.sh
            